name: Build SFML Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-sfml

    - name: Build
      shell: msys2 {0}
      run: |
        g++ src/main.cpp src/planet.cpp \
        -Iheader \
        -o app.exe \
        -lsfml-graphics \
        -lsfml-window \
        -lsfml-system